### ISSUE TITLE
Missin classes at globals.css?

### ISSUE THREAD

**Issue by Tsabary** [danmindru/page-ui#3]
First of all - fantastic project!

I've initialized page-ui following the instructions for Next.js. I am usng the src directory and the App router.

I've noticed that the GlowBg component is always black/colorless?
Is it missing the following variabels?

  const stopColor =
    variant === "primary"
      ? "var(--primary-lighter-hex)"
      : "var(--secondary-lighter-hex)";
  const stopColorTwo =
    variant === "primary"
      ? "var(--primary-dark-hex)"
      : "var(--secondary-dark-hex)";
      
      This is my repo (empty next project with page-ui setup)
      https://github.com/Tsabary/replyke-landing

**Comment by danmindru** [comment]
hey @Tsabary. Thanks so much for the kind words!
Sorry for this, it was a tiny bug indeed.

Could you please add this to your globals.css file (under the :root selector)

```css
:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;

  /* Missing colors */
  --primary-lighter-hex: theme('colors.primary.200');
  --secondary-lighter-hex: theme('colors.secondary.200');
  --primary-dark-hex: theme('colors.primary.800');
  --secondary-dark-hex: theme('colors.secondary.800');
}
```

let me know if you have any issues afterwards!
Dan
